/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Model.glb --transform 
Files: Model.glb [16.49MB] > D:\Projects\Programming\LalitKalaExhibition\public\assets\models\Model-transformed.glb [571.52KB] (97%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Model-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.Object431.geometry} material={materials.PaletteMaterial002} />
      <mesh geometry={nodes.Object312.geometry} material={materials.PaletteMaterial003} />
    </group>
  )
}

useGLTF.preload('/Model-transformed.glb')
