/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 model.glb --transform 
Files: model.glb [41.88MB] > D:\Projects\Programming\LalitKalaExhibition\public\assets\models\model-transformed.glb [1.75MB] (96%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/model-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.Object431.geometry} material={materials.PaletteMaterial002} />
      <mesh geometry={nodes.Object312.geometry} material={materials.PaletteMaterial003} />
      <mesh geometry={nodes.Object1236.geometry} material={materials.PaletteMaterial004} />
      <mesh geometry={nodes.Object2195.geometry} material={materials.PaletteMaterial005} />
      <mesh geometry={nodes.Object2076.geometry} material={materials['Unnamed-1']} />
    </group>
  )
}

useGLTF.preload('/model-transformed.glb')
