/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 model.glb --transform 
Files: model.glb [1086.9MB] > D:\Projects\Programming\LalitKalaExhibition\public\assets\models\model-transformed.glb [14.49MB] (99%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/model-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.Object311.geometry} material={materials.PaletteMaterial002} />
      <mesh geometry={nodes.Object1234.geometry} material={materials.PaletteMaterial003} />
      <mesh geometry={nodes.Object1764.geometry} material={materials['Unnamed-1']} />
      <mesh geometry={nodes.object_26.geometry} material={materials.PaletteMaterial004} />
      <mesh geometry={nodes.object_26001.geometry} material={materials['Роза освещенная светом х.м. 60х40 2019']} />
      <mesh geometry={nodes.object_25001.geometry} material={materials['Святой Христофор-покровитель горо']} />
      <mesh geometry={nodes.object_23001.geometry} material={materials['Сергиев Посад.х.м,40x50,2021']} />
      <mesh geometry={nodes.object_27001.geometry} material={materials['Рождественское утро.60х81.2014']} />
      <mesh geometry={nodes.object_31.geometry} material={materials['Портрет Жана-Поля Готье из серии Р']} />
      <mesh geometry={nodes.object_29.geometry} material={materials['Праздничный пирог.х.м.51х41.2012']} />
      <mesh geometry={nodes.object_28.geometry} material={materials['Предшественник поезда или Машина']} />
      <mesh geometry={nodes.object_38.geometry} material={materials['Мерлин Монро х.м. 51х41 2009г.']} />
      <mesh geometry={nodes.object_33001.geometry} material={materials['Очищение х.м. 50х30 2018г']} />
      <mesh geometry={nodes.object_37.geometry} material={materials['Мираж из прошлого.х.м.31х51.2013']} />
      <mesh geometry={nodes.object_35.geometry} material={materials['Невидящая или Посвящение в рыцари.']} />
      <mesh geometry={nodes.object_34.geometry} material={materials['Новогоднее утро в Москве. х., м.; 40x50;']} />
      <mesh geometry={nodes.object_44.geometry} material={materials['Красоты Азербайджана х.м. 38х51 2017']} />
      <mesh geometry={nodes.object_17001.geometry} material={materials['Тайна дворцовой ночи.х.м.51х41.2013']} />
      <mesh geometry={nodes.object_43.geometry} material={materials['Красоты Владимира вид сверху, х.м. 4']} />
      <mesh geometry={nodes.object_40.geometry} material={materials['Лето в Казани х.м. 40х50 2017']} />
      <mesh geometry={nodes.object_21.geometry} material={materials['Солнечный полдень в Вильнюсе.х.м.52']} />
      <mesh geometry={nodes.object_20.geometry} material={materials['Сон о буддийских драконах после по']} />
      <mesh geometry={nodes.object_19.geometry} material={materials['Страна замков и гор х.м. 40х60 2013 (1)']} />
      <mesh geometry={nodes.object_18.geometry} material={materials['Тайна бытия или Возвращение в детс']} />
      <mesh geometry={nodes.object_67001.geometry} material={materials['Божественная история, выбитая на к']} />
      <mesh geometry={nodes.object_63.geometry} material={materials['Весна из серии Духовная Россия. х.,']} />
      <mesh geometry={nodes.object_8.geometry} material={materials['Цветение сакуры с видом на Фудзиям']} />
      <mesh geometry={nodes.object_10001.geometry} material={materials['Хрупкость бытия или Хрустальная д']} />
      <mesh geometry={nodes.object_9.geometry} material={materials['Хрустальные люди на фоне хрусталь']} />
      <mesh geometry={nodes.object_11.geometry} material={materials['Фил Колинз.х.м.50х60. (2)']} />
      <mesh geometry={nodes.object_73001.geometry} material={materials['4481-Весна-Любовь-х.м.-88х60-2018 (1)']} />
      <mesh geometry={nodes.object_68.geometry} material={materials['Белые ночи. Петропавловская крепо']} />
      <mesh geometry={nodes.object_72001.geometry} material={materials['Алхимик Пауло Коэльо.30х59,2011']} />
      <mesh geometry={nodes.object_71001.geometry} material={materials['Ангел храма или Сон Ангела.х.м.65х40.2']} />
      <mesh geometry={nodes.object_70001.geometry} material={materials['Ангелы.покидающие историю.х.м.40х25,2']} />
      <mesh geometry={nodes['Антихаос_в_истории_космосахм51х39,'].geometry} material={materials['Антихаос в истории космоса.х.м.51х39,']} />
      <mesh geometry={nodes.Девушка_с_моря_или_Предчуствие_пра.geometry} material={materials['Девушка с моря или Предчуствие пра']} />
      <mesh geometry={nodes.object_61.geometry} material={materials['Возвращение во Вселенную.х.м.50х50.200']} />
      <mesh geometry={nodes.object_59.geometry} material={materials['Герой нашего времени.Кевин Костне']} />
      <mesh geometry={nodes.object_58.geometry} material={materials['Год Серебристого быка - 2021 х.м. 40х50 2']} />
      <mesh geometry={nodes.object_65.geometry} material={materials['Весенний Ростов с видом на кафедра']} />
      <mesh geometry={nodes.object_56.geometry} material={materials['Действо на фоне замка.х.м.62х40.2012']} />
      <mesh geometry={nodes.object_51001.geometry} material={materials['Золотое сечение в другом измерени']} />
      <mesh geometry={nodes.object_54.geometry} material={materials['Жизнь х.м. 31х50 1999']} />
      <mesh geometry={nodes.object_53.geometry} material={materials['Зимняя Москва х.м. 30х40 2023 г']} />
      <mesh geometry={nodes.object_50001.geometry} material={materials['И он, как будто околдован, как будт']} />
      <mesh geometry={nodes.object_49001.geometry} material={materials['Из истории Америки. Боги инокв.х.м.4']} />
      <mesh geometry={nodes.object_48001.geometry} material={materials['Из истории гольфа. Дети и шарики.х.']} />
      <mesh geometry={nodes.object_47001.geometry} material={materials['Искусство науки или Алхимия творч']} />
      <mesh geometry={nodes.object_46001.geometry} material={materials['История, созданная из камня.х.м.30х20']} />
      <mesh geometry={nodes['086Николас_Кейджхм50х342009TIF'].geometry} material={materials['086.Николас Кейдж.х.м.50х34.2009 (1)']} />
      <mesh geometry={nodes.object_74.geometry} material={materials['4476 Портрет Анджелины Джоли, Х.М., 40х']} />
      <mesh geometry={nodes['4260_Карнавал_в_Венеции_хм_24х30_2016jpg'].geometry} material={materials['4260 Карнавал в Венеции х.м. 24х30 2016']} />
      <mesh geometry={nodes['4326_Из_истории_Азербайджана_хм50х60'].geometry} material={materials['4326 Из истории Азербайджана х.м.50х60']} />
      <mesh geometry={nodes['4337_Из_Истории_Азербайджана_Девушк'].geometry} material={materials['4337 Из Истории Азербайджана Девушк']} />
      <mesh geometry={nodes.object_75001.geometry} material={materials['4474 Тим Рот или возврат к Леонардо,']} />
      <mesh geometry={nodes.object_16001.geometry} material={materials['Тайна дома Б.х.м.50х36.2012']} />
      <mesh geometry={nodes.object_12.geometry} material={materials['Утренний летний сон об Италии.х.м.50']} />
      <mesh geometry={nodes.object_15001.geometry} material={materials['Тайна замка одной любовной истори']} />
      <mesh geometry={nodes.object_14001.geometry} material={materials['Тайна ночи окутанная .... 52х42 1989-2016']} />
      <mesh geometry={nodes.object_13001.geometry} material={materials['Уильям Дефо.х.м.62х41,2011']} />
      <mesh geometry={nodes.object_6.geometry} material={materials['Цветы, посвященные Жану Фуке.х.м.52х']} />
      <mesh geometry={nodes.object_4001.geometry} material={materials['Этюд Венеция х.м. 30х50 2020']} />
      <mesh geometry={nodes.object_5.geometry} material={materials['Человек,манипулирующий временем.х']} />
      <mesh geometry={nodes.object_3001.geometry} material={materials['Явление апостолов в небе, воспеваю']} />
      <mesh geometry={nodes.object_1.geometry} material={materials['лето в предгорье на оне замка']} />
      <mesh geometry={nodes.object_2001.geometry} material={materials['и Дух Святой.х.м.40х42']} />
      <mesh geometry={nodes.object_7.geometry} material={materials['Цветущий май, х.м., 50х30, 2008']} />
    </group>
  )
}

useGLTF.preload('/model-transformed.glb')
